//! Generated protobuf types for poker examples.
//!
//! Re-exports the contents of `angzarr_client.proto.examples` at the
//! crate root so callers can write `examples_proto::PlayerRegistered`
//! the same way they did before the canonical proto package rename.
//!
//! Generated by `just generate-proto` (cross-language proto generation
//! model — see project_proto_generation_model.md). The included file is
//! emitted into `proto/src/generated/` and gitignored; lefthook fires
//! `just generate-proto` on post-checkout / post-merge.

mod inner {
    include!("generated/angzarr_client.proto.examples.rs");
}

pub use inner::*;
